avatar: /img/touxiang.png
author: Zero
subtitle: "胆小怕事, 不善交流"
about: "Zero<br>专科生, 自学安卓<br><br>爱折腾<br>一名Android开发Coder<br><br>克服社交障碍中..."
github: https://github.com/Tan-yi-xiong
weibo: https://weibo.com/u/3542658790
